version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "8088:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - mysql
    networks:
      - laravel-net

  # MySQL Database
  mysql:
    image: mysql:8
    container_name: laravel-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: your_database_user_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - laravel-net

networks:
  laravel-net:
