pipeline {
    agent any

    environment {
        DB_ROOT_PASSWORD = 'your_database_root_password'
        DB_DATABASE = 'laravel'
        DB_USERNAME = 'root'
        DB_PASSWORD = 'your_database_user_password'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/AvishkaKoswatta/DevOps_project6.git' // Replace with your repository URL
            }
        }
        
        stage('Build Docker Images') {
            steps {
                script {
                    // Build Laravel app image
                    def appImage = docker.build('laravel-app', './laravel')

                    // Build MySQL image if you have custom configurations
                    // def mysqlImage = docker.build('mysql', './mysql') // Uncomment if needed
                }
            }
        }

        stage('Run Docker Containers') {
            steps {
                script {
                    // Use docker-compose to bring up the services
                    sh 'docker-compose up -d'
                }
            }
        }
        
        stage('Run Migrations') {
            steps {
                script {
                    // Run migrations
                    sh 'docker-compose exec laravel-app php artisan migrate'
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                script {
                    // Run tests
                    sh 'docker-compose exec laravel-app php artisan test'
                }
            }
        }

        stage('Clean Up') {
            steps {
                script {
                    // Bring down the services and remove volumes
                    sh 'docker-compose down --volumes'
                }
            }
        }
    }
}
