pipeline {
    agent any

    environment {
        DB_ROOT_PASSWORD = 'your_database_root_password'
        DB_DATABASE = 'laravel'
        DB_USERNAME = 'root'
        DB_PASSWORD = 'your_database_user_password'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/AvishkaKoswatta/DevOps_project6.git' // Replace with your repository URL
            }
        }
        
        stage('Build Docker Images') {
            steps {
                script {
                    docker.build('laravel-app', './laravel')
                }
            }
        }

        stage('Run Docker Containers') {
            steps {
                script {
                    docker.compose.up '-d'
                }
            }
        }
        
        stage('Run Migrations') {
            steps {
                script {
                    docker.compose.exec('laravel-app', 'php artisan migrate')
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                script {
                    docker.compose.exec('laravel-app', 'php artisan test')
                }
            }
        }

        stage('Clean Up') {
            steps {
                script {
                    docker.compose.down '--volumes'
                }
            }
        }
    }
}
